<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Gym_Store</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Chief Collagen Bar  – Double Chocolate.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\EHP Labs Pride Pre-Workout Blue Slushie.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\EHP Labs Pride Pre-Workout Raspberry Twizzle.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Ghost Whey Protein - Coffee Ice Cream.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Ghost Whey Protein - Marshmallow.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Grenade Protein Bar - Fudge Up.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Grenade Protein Bar - Oreo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Horleys Protein 33 Low Carb Bars - Double Chocolate Fudge.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\INC Creatine Monohydrate.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Musashi 100%25 Creatine.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Musashi Pre-Workout Purple Grape.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Musashi Protein + Energy Bars - Banana Bread.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Musashi Shred &amp; Burn Protein – Chocolate Milkshake.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Musashi Shred &amp; Burn Protein – Vanilla Milkshake.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Myprotein Impact Whey Isolate.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Optimum Nutrition Gold Standard 100% Whey - French Vanilla.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Optimum Nutrition Gold Standard 100%25 Whey - Cookies &amp; Cream.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Optimum Nutrition Gold Standard Pre-Workout Blueberry Lemonade.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Optimum Nutrition Gold Standard Pre-Workout Green Apple.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images - Back Up\Optimum Nutrition Micronised Creatine Powder.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Chief Collagen Bar  – Double Chocolate.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\EHP Labs Pride Pre-Workout Blue Slushie.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\EHP Labs Pride Pre-Workout Raspberry Twizzle.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Ghost Whey Protein - Coffee Ice Cream.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Ghost Whey Protein - Marshmallow.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Grenade Protein Bar - Fudge Up.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Grenade Protein Bar - Oreo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Horleys Protein 33 Low Carb Bars - Double Chocolate Fudge.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\INC Creatine Monohydrate.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Musashi 100%25 Creatine.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Musashi Pre-Workout Purple Grape.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Musashi Protein + Energy Bars - Banana Bread.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Musashi Shred &amp; Burn Protein – Chocolate Milkshake.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Musashi Shred &amp; Burn Protein – Vanilla Milkshake.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Myprotein Impact Whey Isolate.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Optimum Nutrition Gold Standard 100%25 Whey - Cookies &amp; Cream.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Optimum Nutrition Gold Standard 100%25 Whey - French Vanilla.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Optimum Nutrition Gold Standard Pre-Workout Blueberry Lemonade.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Optimum Nutrition Gold Standard Pre-Workout Green Apple.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Gym_Store\Images\Optimum Nutrition Micronised Creatine Powder.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Identity\Data\" />
    <Folder Include="Controllers\Admin\" />
    <Folder Include="Controllers\Customer\" />
    <Folder Include="Views\Admin\" />
    <Folder Include="Views\Customer\" />
  </ItemGroup>

</Project>
