// <auto-generated />
using System;
using Gym_Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym_Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250518171620_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym_Store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Protein Powder"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Creatine Supplement"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pre-Workout"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Protein Bars"
                        });
                });

            modelBuilder.Entity("Gym_Store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "/Gym_Store/Images/Optimum Nutrition Gold Standard 100% Whey - French Vanilla.jpg",
                            Name = "Optimum Nutrition Gold Standard 100% Whey - French Vanilla",
                            Price = 98.95m,
                            Quantity = "2.27 kg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageUrl = "/Gym_Store/Images/Myprotein Impact Whey Isolate.jpg",
                            Name = "Myprotein Impact Whey Isolate",
                            Price = 70.50m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            ImageUrl = "/Gym_Store/Images/INC Creatine Monohydrate.jpg",
                            Name = "INC Creatine Monohydrate",
                            Price = 39.95m,
                            Quantity = "500 g"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            ImageUrl = "/Gym_Store/Images/EHP Labs Pride Pre-Workout Blue Slushie.jpg",
                            Name = "EHP Labs Pride Pre-Workout Blue Slushie",
                            Price = 79.95m,
                            Quantity = "40 Serves"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            ImageUrl = "/Gym_Store/Images/EHP Labs Pride Pre-Workout Raspberry Twizzle.jpg",
                            Name = "EHP Labs Pride Pre-Workout Raspberry Twizzle",
                            Price = 79.95m,
                            Quantity = "40 Serves"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ImageUrl = "/Gym_Store/Images/Optimum Nutrition Gold Standard Pre-Workout Green Apple.jpg",
                            Name = "Optimum Nutrition Gold Standard Pre-Workout Green Apple",
                            Price = 39.90m,
                            Quantity = "30 Serves"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            ImageUrl = "/Gym_Store/Images/Optimum Nutrition Gold Standard Pre-Workout Blueberry Lemonade.jpg",
                            Name = "Optimum Nutrition Gold Standard Pre-Workout Blueberry Lemonade",
                            Price = 39.90m,
                            Quantity = "30 Serves"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            ImageUrl = "/Gym_Store/Images/Musashi Pre-Workout Purple Grape.jpg",
                            Name = "Musashi Pre-Workout Purple Grape",
                            Price = 29.99m,
                            Quantity = "225 g"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            ImageUrl = "/Gym_Store/Images/Optimum Nutrition Micronised Creatine Powder.jpg",
                            Name = "Optimum Nutrition Micronised Creatine Powder",
                            Price = 39.95m,
                            Quantity = "300 G"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ImageUrl = "/Gym_Store/Images/Musashi 100% Creatine.jpg",
                            Name = "Musashi 100% Creatine",
                            Price = 32.95m,
                            Quantity = "350 G"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            ImageUrl = "/Gym_Store/Images/Musashi Shred & Burn Protein – Vanilla Milkshake.jpg",
                            Name = "Musashi Shred & Burn Protein – Vanilla Milkshake",
                            Price = 110.46m,
                            Quantity = "2 kg"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            ImageUrl = "/Gym_Store/Images/Musashi Shred & Burn Protein – Chocolate Milkshake.jpg",
                            Name = "Musashi Shred & Burn Protein – Chocolate Milkshake",
                            Price = 110.46m,
                            Quantity = "2 kg"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            ImageUrl = "/Gym_Store/Images/Grenade Protein Bar - Oreo.jpg",
                            Name = "Grenade Protein Bar - Oreo",
                            Price = 59.95m,
                            Quantity = "12 x 60 G"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            ImageUrl = "/Gym_Store/Images/Chief Collagen Bar  – Double Chocolate.jpg",
                            Name = "Chief Collagen Bar  – Double Chocolate",
                            Price = 63.00m,
                            Quantity = "12x 60g"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            ImageUrl = "/Gym_Store/Images/Grenade Protein Bar - Fudge Up.jpg",
                            Name = "Grenade Protein Bar - Fudge Up",
                            Price = 59.95m,
                            Quantity = "12 x 60 G"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            ImageUrl = "/Gym_Store/Images/Horleys Protein 33 Low Carb Bars - Double Chocolate Fudge.jpg",
                            Name = "Horleys Protein 33 Low Carb Bars - Double Chocolate Fudge",
                            Price = 34.95m,
                            Quantity = "12x 60g"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            ImageUrl = "/Gym_Store/Images/Musashi Protein + Energy Bars - Banana Bread.jpg",
                            Name = "Musashi Protein + Energy Bars - Banana Bread",
                            Price = 39.96m,
                            Quantity = "12x 58g"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            ImageUrl = "/Gym_Store/Images/Optimum Nutrition Gold Standard 100% Whey - Cookies & Cream.jpg",
                            Name = "Optimum Nutrition Gold Standard 100% Whey - Cookies & Cream",
                            Price = 98.95m,
                            Quantity = "2.27 kg"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            ImageUrl = "/Gym_Store/Images/Ghost Whey Protein - Coffee Ice Cream.jpg",
                            Name = "Ghost Whey Protein - Coffee Ice Cream",
                            Price = 89.00m,
                            Quantity = "2.27 kg"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            ImageUrl = "/Gym_Store/Images/Ghost Whey Protein - Marshmallow.jpg",
                            Name = "Ghost Whey Protein - Marshmallow",
                            Price = 89.00m,
                            Quantity = "2.27 kg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Gym_Store.Models.Product", b =>
                {
                    b.HasOne("Gym_Store.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
